name: imago_vox
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_tts: ^3.8.0
  google_mlkit_text_recognition: ^0.13.0
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  file_picker: ^8.0.6
  image: ^4.2.0
  nb_utils: ^7.0.2
  go_router: ^10.1.2
  toastification: ^1.2.1
  camera: ^0.11.0+1
  lottie: ^2.6.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/lotties/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
